name: shared_ui_components
description: A shared library for `BeWell-Consumer` and `BeWell-Professional` that is responsible for rendering and exposing dumb widgets and ui components
version: 0.2.2-nullsafety
homepage: https://github.com/savannahghi/shared_ui_components
repository: https://github.com/savannahghi/shared_ui_components
issue_tracker: https://github.com/savannahghi/shared_ui_components/issues
documentation: https://github.com/savannahghi/shared_ui_components/blob/main/doc/readme.md

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  http: ^0.13.5
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6996
  misc_utilities: ^0.2.0-nullsafety
  pin_code_text_field: ^1.8.0
  platform: ^3.1.0
  rxdart: ^0.27.5
  shared_themes: ^0.1.0 # internal (formerly sil_themes)
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - packages/shared_ui_components/assets/ken.png
    - packages/shared_ui_components/assets/try_features.jpg
    - packages/shared_ui_components/assets/test-development.png
    - packages/shared_ui_components/assets/tza.png
    - packages/shared_ui_components/assets/uga.png
    - packages/shared_ui_components/assets/usa.png
    - packages/shared_ui_components/assets/gbr.png
    - packages/shared_ui_components/assets/bel.png
    - packages/shared_ui_components/assets/nga.png
    - packages/shared_ui_components/assets/close.png
    - packages/shared_ui_components/assets/error.svg
    - packages/shared_ui_components/assets/info.svg
    - packages/shared_ui_components/assets/success.svg
