name: shared_ui_components
description: A shared library for `BeWell-Consumer` and `BeWell-Professional` that is responsible for rendering and exposing dumb widgets and ui components
version: 0.1.24-nullsafety
homepage: https://github.com/savannahghi/shared_ui_components
repository: https://github.com/savannahghi/shared_ui_components
issue_tracker: https://github.com/savannahghi/shared_ui_components/issues
documentation: https://github.com/savannahghi/shared_ui_components/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  misc_utilities: ^0.1.14-nullsafety # internal (formerly sil_misc)
  pin_code_text_field: ^1.8.0
  rxdart: ^0.27.1
  shared_themes: ^0.0.9 # internal (formerly sil_themes)

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - packages/shared_ui_components/assets/ke.png
    - packages/shared_ui_components/assets/try_features.jpg
    - packages/shared_ui_components/assets/test-development.png
    - packages/shared_ui_components/assets/tz.png
    - packages/shared_ui_components/assets/ug.png
    - packages/shared_ui_components/assets/us.png
    - packages/shared_ui_components/assets/uk.png
    - packages/shared_ui_components/assets/bel.png
    - packages/shared_ui_components/assets/close.png
    - packages/shared_ui_components/assets/error.svg
    - packages/shared_ui_components/assets/info.svg
    - packages/shared_ui_components/assets/success.svg
