name: shared_ui_components CI/CD Workflow

on: [push]

jobs: 
  run-tests-and-coverage: 
    name: Analyze, test and report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - uses: actions/setup-python@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.0.3'

      - name: Install flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Analyze and Test
        run: |
          flutter analyze
          sudo apt-get -qq update
          sudo apt-get install -qqy lcov python3-pip 
          pip3 install -Uqqq lxml && pip3 install -Uqqq beautifulsoup4
          flutter test --coverage test/ 
          genhtml -q -o coverage coverage/lcov.info
          python3 check_coverage.py



# name: Publish package to pub.dev
# on:
#   push:
#     branches:   
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Setup credentials
#       run: | 
#         mkdir -p ~/.pub-cache 
#         cat <<EOF > ~/.pub-cache/credentials.json
#         {
#           "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
#           "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
#           "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
#           "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
#           "expiration": 1570721159347
#         }
#         EOF
#     - name: Publish package
#       run: pub publish -f